### PR TITLE
Fix brow LM indices left/right

### PR DESCRIPTION
**Pull request by avaer**
I don't know if this is 100% correct, but it seems the brow landmark point indices are mirrored, or at least do not match the pupil side, which messes up the pupils solve because the brows are the bounding box of the pupils.

I don't know if it matters but I'm using `holistic` latest model.

In my testing I found the pupils math is completely messed up because of this bug -- it is "corrected" by some additional averaging of both eyes, which "fixes" the error but adds a lot of jitter to the pupil tracking. https://github.com/yeemachine/kalidokit/blob/73f202663c32673f7e21c8869bf02f81223bc340/src/FaceSolver/calcEyes.js#L97

### CODE REVIEW

**Comment by avaer** [comment]
IMO once this bug is fixed, the pupils math can be revised to be cleaner and more accurate.

**Comment by yeemachine** [comment]
Hmm, for the pupil solver, perhaps there's some weirdness in the points, made even greater with the new Holistic model release. That said, I haven't confirmed yet if the brows were flipped or not, but they shouldn't impact the pupil points since it only uses the eye and pupil landmarks. So if there are issues with the pupils, perhaps the points just need to be updated?

https://github.com/yeemachine/kalidokit/blob/73f202663c32673f7e21c8869bf02f81223bc340/src/FaceSolver/calcEyes.js#L97

This is the diagram I am referencing, hopefully it is up to date. 
https://raw.githubusercontent.com/tensorflow/tfjs-models/master/face-landmarks-detection/mesh_map.jpg

**Comment by avaer** [comment]
> This is the diagram I am referencing, hopefully it is up to date.
> https://raw.githubusercontent.com/tensorflow/tfjs-models/master/face-landmarks-detection/mesh_map.jpg

Thanks, I was looking for that. I wish it were greppable though, like an SVG, because I think the brows were flipped (relative to the pupils) when I was visualizing it.

> So if there are issues with the pupils, perhaps the points just need to be updated?

Yes, I'll try some more things, since the pupils behave very weird for me.

I still think the brows are flipped in my visualization though and this PR fixes the flip.

**Comment by yeemachine** [comment]
Thanks! merged.

**Comment by avaer** [comment]
Actually I think I was wrong on this, the brow was correct but the eye was not. I'll show some samples and make another PR.

Thanks for your work on this!

**Comment by yeemachine** [comment]
whoops. rookie mistake of not checking more thoroughly. ive reverted things on my end as well as update the js comments

**Pull request merged**
