### PR TITLE
Improve leg and arm rotation

### PR DESCRIPTION
**Pull request by utileetdulce**
# Improvement of Leg and Arm Rotation

Hi Rich, It took some time and I am not 100% satisfied with this solution, but I think it is an improvement. 
What has changed:
- Types for left and right
- Unit test for upper and lower legs
- Alternative calculation for the leg rotation
- Alternative calculation for the arm rotation 
- Introduction of a Euler Class to keep track of the rotation order (especially import for the arm rotations)
- A little code cleaning 
- The use of constants for PI and TWO_PI

I'm looking forward to your feedback!

### CODE REVIEW

**Comment by yeemachine** [comment]
Appreciate the hard work! Can't wait to test it out this weekend!

**Comment by utileetdulce** [comment]
Great! You can try to use another rotation order for the legs (https://github.com/utileetdulce/kalidokit/blob/improve-leg-and-arm-rotation/src/PoseSolver/calcLegs.ts#L104). In my tests, "XYZ", "YZX", "XZY" and "YXZ" also gave good results, but none of them is perfect. You may find a solution to this problem or choose the most suitable version. Here is a preview: 

https://user-images.githubusercontent.com/40870660/151511293-d5e0c280-6192-4424-8580-640ffe75b38a.mp4

**Comment by ButzYung** [comment]
The preview looks promising. I am working on a similar app which also requires translating mediapipe/TFJS detected positions to 3D model bone rotation. I am using a somewhat different approach, and just like what you said I am not 100% satisfied with my solution as well lol. It will be interesting to see which solution is better, or if there is still a better solution out there.

**Review by AlenVelocity — CHANGES_REQUESTED** [review]
Great Work @utileetdulce. Could you edit the workflow that it runs the tests as well? 
This can be done by adding `npm run jest` as it's own line in the build workflow file

**Comment by yeemachine** [comment]
Took a chance to preview the new approach. I do think that the leg rotations are much better! However, the arm calcs are a bit wonkier than the current implementation, especially when trying to raise arms overhead. Maybe we move this to a `dev` branch first before introducing it to `main`.

**Comment by utileetdulce** [comment]
> Great Work @utileetdulce. Could you edit the workflow that it runs the tests as well? This can be done by adding `npm run jest` as it's own line in the build workflow file

I just added a single line command for the unit tests to the build workflow. I am not very familiar with github workflows, but maybe we could use a multi-line command instead?

**Comment by utileetdulce** [comment]
> Took a chance to preview the new approach. I do think that the leg rotations are much better! However, the arm calcs are a bit wonkier than the current implementation, especially when trying to raise arms overhead. Maybe we move this to a `dev` branch first before introducing it to `main`.

yes, that sounds like a good way to go. I could also extract the arm calculation in separate branch, if you prefer that.

**Comment by yeemachine** [comment]
> 

Hmm, if there's a way to use the leg calcs from your solution and keep the current arm implementation, we could possibly merge this into main a bit quicker. Else, we prob need to make arm calcs more stable before merging. What do you think? 

Main problems I do see is the inconsistency when raising arms, and sometimes the arms will twist like a corkscrew.

**Comment by utileetdulce** [comment]
> Else, we prob need to make arm calcs more stable before merging. What do you think?

I just tested it again and I have to admit that my approach for the arms has more drawbacks than benefits. I suggest to remove the arm rotation from this branch/pull request. I will open another pull request if I can improve the arms. 

Background information: I do not use VRM models, but rigged character models in .glb format (rigged, like models from Mixamo). So I need to map the axes and apply other options like offset, min, max, inverse, rotation-order to fit the specific model. Also, I only need the pose solver for my project.

**Comment by yeemachine** [comment]
Removed 98b9739 and merged into `dev` branch. I think it's working fairly well. I'll do some more tests later this week before merging with `main`. 

Thank you again for your contribution @utileetdulce. Totally understand that rotation axis are different for different model types (part of the reason why this project is currently euler based and not quaternion base despite gimble lock implications). Getting legs into KalidoKit is def a big deal! People will def appreciate this update. Wish you the best in your personal project as well!

**Comment by utileetdulce** [comment]
@yeemachine thank you. Without the arm calculation and with the rotation order for the legs being "XYZ", which is the default, you might want to revert the Euler class/type changes as well.

**Comment by ButzYung** [comment]
> Totally understand that rotation axis are different for different model types (part of the reason why this project is currently euler based and not quaternion base despite gimble lock implications).

Maybe you really should consider using quaternion in the first place. I remembered the time when I was struggling between choosing euler and quaternion to deal with this kind of problem, and at the end I choose quaternion. While quaternion has complications of its own (like the multiplication order and difficulties to limit the rotation), it still saves more headaches than dealing with euler.

**Comment by zhangsirya** [comment]
Please may I ask where the blendshape data for pose estimation is obtained from?

**Pull request merged**
