### PR TITLE
Fix: 'Cannot find type definition file for 'node'.' when using yarn to install dependencies

### PR DESCRIPTION
**Pull request by LehaoLin**
Add yarn.lock file when using `yarn` to install dependencies
and fix the error, showing "Cannot find type definition file for 'node'." message when yarn `tsc -p .` building.
Error messages shown below:
```
> kalidokit@1.1.2 build:lib
> tsc -p .

../../node_modules/@types/plist/index.d.ts:7:23 - error TS2688: Cannot find type definition file for 'node'.

7 /// <reference types="node" />
                        ~~~~

../../node_modules/@types/plist/index.d.ts:21:10 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

21   Date | Buffer | PlistObject | PlistArray;
            ~~~~~~

../../node_modules/@types/responselike/index.d.ts:6:23 - error TS2688: Cannot find type definition file for 'node'.

6 /// <reference types="node" />
                        ~~~~

../../node_modules/@types/responselike/index.d.ts:8:33 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

8 import { IncomingMessage } from 'http';
                                  ~~~~~~

../../node_modules/@types/responselike/index.d.ts:9:24 - error TS2307: Cannot find module 'stream' or its corresponding type declarations.

9 import { Stream } from 'stream';
                         ~~~~~~~~

../../node_modules/@types/responselike/index.d.ts:19:11 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

19     body: Buffer;
             ~~~~~~

../../node_modules/@types/responselike/index.d.ts:31:15 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

31         body: Buffer,
                 ~~~~~~

../../node_modules/xmlbuilder/typings/index.d.ts:2:26 - error TS2307: Cannot find module 'stream' or its corresponding type declarations.

2 import { Writable } from 'stream';
                           ~~~~~~~~


Found 8 errors.

error Command failed with exit code 2.```

### CODE REVIEW

**Comment by LehaoLin** [comment]
The above error message also appears when using `npm i`.
I think it is necessary to add `"@types/node": "^17.0.5"` package in the `devDependencies`.

**Comment by AlenVelocity** [comment]
Kalidokit does not depend on any modules from the node standard library. Those errors are possibly coming from an external lib. Plus it's nit ideal to use multiple package mangers in a single project, so the `yarn.lock` file is redundant

**Comment by AlenVelocity** [comment]
Could you share what command you used to install Kalidokit? (which threw this error)

**Comment by LehaoLin** [comment]
> Could you share what command you used to install Kalidokit? (which threw this error)

@AlenSaito1 
I just `git clone` this repo and then `npm i` (same as `yarn`) to install independencies. Then the error appears.

**Comment by yeemachine** [comment]
So far, `@types/node` has not been needed for `npm i` in the workflows I've tested. Currently running `node v14.18.0` without any issues. And we should avoid `yarn-lock` and having multiple package managers for KalidoKit. 

Will close this request for now, but we can revisit it if more issues like this are reported.

**Pull request closed without merging**
